### ISSUE TITLE
Website not working.

### ISSUE THREAD

**Issue by sesn** [jshor/tycho#4]
***Access origin header denied for this domain https://cdn.tycho.io***

```Failed to load https://cdn.tycho.io/static/data/pageText.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://tycho.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by jshor** [comment]
@sesn yep, was an AWS issue. Should work now.
